server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
   
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: questions
        uri: lb://questions   
        predicates:
        - Path=**/questions/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
